//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundXchange.Model.AuthenticationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionResultOfUserDTOcAGUi1Ju", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.ActionResults")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FundXchange.Model.AuthenticationService.UserResult))]
    public partial class ActionResultOfUserDTOcAGUi1Ju : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.UserDTO ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.ResultTypes ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.UserDTO Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.ResultTypes Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.AccountDto AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.AlertScriptDTO[] AlertScriptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.AlertDTO[] AlertsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.BrokerageAccountDTO[] BrokerageAccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.DataPortfolioDTO[] DataPortfoliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.PersonalDetailsDto PersonalDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.RoyaltyAgreementDTO[] RoyaltyAgreementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.ScannerDTO[] ScannersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.ServiceCodeDTO[] ServiceCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.SubscriptionStatuses SubscriptionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TrialStartedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.AccountDto Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.AlertScriptDTO[] AlertScripts {
            get {
                return this.AlertScriptsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertScriptsField, value) != true)) {
                    this.AlertScriptsField = value;
                    this.RaisePropertyChanged("AlertScripts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.AlertDTO[] Alerts {
            get {
                return this.AlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertsField, value) != true)) {
                    this.AlertsField = value;
                    this.RaisePropertyChanged("Alerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.BrokerageAccountDTO[] BrokerageAccounts {
            get {
                return this.BrokerageAccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerageAccountsField, value) != true)) {
                    this.BrokerageAccountsField = value;
                    this.RaisePropertyChanged("BrokerageAccounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.DataPortfolioDTO[] DataPortfolios {
            get {
                return this.DataPortfoliosField;
            }
            set {
                if ((object.ReferenceEquals(this.DataPortfoliosField, value) != true)) {
                    this.DataPortfoliosField = value;
                    this.RaisePropertyChanged("DataPortfolios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.PersonalDetailsDto PersonalDetails {
            get {
                return this.PersonalDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalDetailsField, value) != true)) {
                    this.PersonalDetailsField = value;
                    this.RaisePropertyChanged("PersonalDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.RoyaltyAgreementDTO[] RoyaltyAgreements {
            get {
                return this.RoyaltyAgreementsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoyaltyAgreementsField, value) != true)) {
                    this.RoyaltyAgreementsField = value;
                    this.RaisePropertyChanged("RoyaltyAgreements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.ScannerDTO[] Scanners {
            get {
                return this.ScannersField;
            }
            set {
                if ((object.ReferenceEquals(this.ScannersField, value) != true)) {
                    this.ScannersField = value;
                    this.RaisePropertyChanged("Scanners");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.ServiceCodeDTO[] ServiceCodes {
            get {
                return this.ServiceCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodesField, value) != true)) {
                    this.ServiceCodesField = value;
                    this.RaisePropertyChanged("ServiceCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.SubscriptionStatuses SubscriptionStatus {
            get {
                return this.SubscriptionStatusField;
            }
            set {
                if ((this.SubscriptionStatusField.Equals(value) != true)) {
                    this.SubscriptionStatusField = value;
                    this.RaisePropertyChanged("SubscriptionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TrialStarted {
            get {
                return this.TrialStartedField;
            }
            set {
                if ((this.TrialStartedField.Equals(value) != true)) {
                    this.TrialStartedField = value;
                    this.RaisePropertyChanged("TrialStarted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResult", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.ActionResults")]
    [System.SerializableAttribute()]
    public partial class UserResult : FundXchange.Model.AuthenticationService.ActionResultOfUserDTOcAGUi1Ju {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultTypes", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.ActionResults")]
    public enum ResultTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDto", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class AccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataVendorAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataVendor_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataVendor_UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.PaymentModelTypes PaymentModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataVendorAccountId {
            get {
                return this.DataVendorAccountIdField;
            }
            set {
                if ((this.DataVendorAccountIdField.Equals(value) != true)) {
                    this.DataVendorAccountIdField = value;
                    this.RaisePropertyChanged("DataVendorAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataVendor_Password {
            get {
                return this.DataVendor_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.DataVendor_PasswordField, value) != true)) {
                    this.DataVendor_PasswordField = value;
                    this.RaisePropertyChanged("DataVendor_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataVendor_Username {
            get {
                return this.DataVendor_UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataVendor_UsernameField, value) != true)) {
                    this.DataVendor_UsernameField = value;
                    this.RaisePropertyChanged("DataVendor_Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.PaymentModelTypes PaymentModel {
            get {
                return this.PaymentModelField;
            }
            set {
                if ((this.PaymentModelField.Equals(value) != true)) {
                    this.PaymentModelField = value;
                    this.RaisePropertyChanged("PaymentModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((this.ProductField.Equals(value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class PersonalDetailsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.Salutations SalutationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellphone {
            get {
                return this.CellphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellphoneField, value) != true)) {
                    this.CellphoneField = value;
                    this.RaisePropertyChanged("Cellphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.Salutations Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((this.SalutationField.Equals(value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertScriptDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class AlertScriptDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbbreviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DayHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EndOfDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitLongScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitShortScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GTCHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUserDefinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MarketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NumberOfLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortfolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StopLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StopLimitValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StopMarketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeSignalScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UniqueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abbreviation {
            get {
                return this.AbbreviationField;
            }
            set {
                if ((object.ReferenceEquals(this.AbbreviationField, value) != true)) {
                    this.AbbreviationField = value;
                    this.RaisePropertyChanged("Abbreviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertName {
            get {
                return this.AlertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertNameField, value) != true)) {
                    this.AlertNameField = value;
                    this.RaisePropertyChanged("AlertName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bars {
            get {
                return this.BarsField;
            }
            set {
                if ((this.BarsField.Equals(value) != true)) {
                    this.BarsField = value;
                    this.RaisePropertyChanged("Bars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyScript {
            get {
                return this.BuyScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyScriptField, value) != true)) {
                    this.BuyScriptField = value;
                    this.RaisePropertyChanged("BuyScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DayHours {
            get {
                return this.DayHoursField;
            }
            set {
                if ((this.DayHoursField.Equals(value) != true)) {
                    this.DayHoursField = value;
                    this.RaisePropertyChanged("DayHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultScript {
            get {
                return this.DefaultScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultScriptField, value) != true)) {
                    this.DefaultScriptField = value;
                    this.RaisePropertyChanged("DefaultScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EndOfDay {
            get {
                return this.EndOfDayField;
            }
            set {
                if ((this.EndOfDayField.Equals(value) != true)) {
                    this.EndOfDayField = value;
                    this.RaisePropertyChanged("EndOfDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exchange {
            get {
                return this.ExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeField, value) != true)) {
                    this.ExchangeField = value;
                    this.RaisePropertyChanged("Exchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitLongScript {
            get {
                return this.ExitLongScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitLongScriptField, value) != true)) {
                    this.ExitLongScriptField = value;
                    this.RaisePropertyChanged("ExitLongScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitShortScript {
            get {
                return this.ExitShortScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitShortScriptField, value) != true)) {
                    this.ExitShortScriptField = value;
                    this.RaisePropertyChanged("ExitShortScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GTC {
            get {
                return this.GTCField;
            }
            set {
                if ((this.GTCField.Equals(value) != true)) {
                    this.GTCField = value;
                    this.RaisePropertyChanged("GTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GTCHours {
            get {
                return this.GTCHoursField;
            }
            set {
                if ((this.GTCHoursField.Equals(value) != true)) {
                    this.GTCHoursField = value;
                    this.RaisePropertyChanged("GTCHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUserDefined {
            get {
                return this.IsUserDefinedField;
            }
            set {
                if ((this.IsUserDefinedField.Equals(value) != true)) {
                    this.IsUserDefinedField = value;
                    this.RaisePropertyChanged("IsUserDefined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((this.LimitField.Equals(value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Market {
            get {
                return this.MarketField;
            }
            set {
                if ((this.MarketField.Equals(value) != true)) {
                    this.MarketField = value;
                    this.RaisePropertyChanged("Market");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NumberOfLines {
            get {
                return this.NumberOfLinesField;
            }
            set {
                if ((this.NumberOfLinesField.Equals(value) != true)) {
                    this.NumberOfLinesField = value;
                    this.RaisePropertyChanged("NumberOfLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodField, value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Portfolio {
            get {
                return this.PortfolioField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioField, value) != true)) {
                    this.PortfolioField = value;
                    this.RaisePropertyChanged("Portfolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellScript {
            get {
                return this.SellScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.SellScriptField, value) != true)) {
                    this.SellScriptField = value;
                    this.RaisePropertyChanged("SellScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StopLimit {
            get {
                return this.StopLimitField;
            }
            set {
                if ((this.StopLimitField.Equals(value) != true)) {
                    this.StopLimitField = value;
                    this.RaisePropertyChanged("StopLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StopLimitValue {
            get {
                return this.StopLimitValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StopLimitValueField, value) != true)) {
                    this.StopLimitValueField = value;
                    this.RaisePropertyChanged("StopLimitValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StopMarket {
            get {
                return this.StopMarketField;
            }
            set {
                if ((this.StopMarketField.Equals(value) != true)) {
                    this.StopMarketField = value;
                    this.RaisePropertyChanged("StopMarket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeSignalScript {
            get {
                return this.TradeSignalScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeSignalScriptField, value) != true)) {
                    this.TradeSignalScriptField = value;
                    this.RaisePropertyChanged("TradeSignalScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((this.UniqueIdField.Equals(value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class AlertDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.AlertType AlertTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertName {
            get {
                return this.AlertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertNameField, value) != true)) {
                    this.AlertNameField = value;
                    this.RaisePropertyChanged("AlertName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.AlertType AlertType {
            get {
                return this.AlertTypeField;
            }
            set {
                if ((this.AlertTypeField.Equals(value) != true)) {
                    this.AlertTypeField = value;
                    this.RaisePropertyChanged("AlertType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exchange {
            get {
                return this.ExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeField, value) != true)) {
                    this.ExchangeField = value;
                    this.RaisePropertyChanged("Exchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerageAccountDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class BrokerageAccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.BrokerageTypes BrokerageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.BrokerageTypes BrokerageType {
            get {
                return this.BrokerageTypeField;
            }
            set {
                if ((this.BrokerageTypeField.Equals(value) != true)) {
                    this.BrokerageTypeField = value;
                    this.RaisePropertyChanged("BrokerageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPortfolioDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class DataPortfolioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.InstrumentDTO[] InstrumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortfolioNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.InstrumentDTO[] Instruments {
            get {
                return this.InstrumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstrumentsField, value) != true)) {
                    this.InstrumentsField = value;
                    this.RaisePropertyChanged("Instruments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortfolioName {
            get {
                return this.PortfolioNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioNameField, value) != true)) {
                    this.PortfolioNameField = value;
                    this.RaisePropertyChanged("PortfolioName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoyaltyAgreementDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class RoyaltyAgreementDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RoyaltyAgreementIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoyaltyAgreementIdentifier {
            get {
                return this.RoyaltyAgreementIdentifierField;
            }
            set {
                if ((this.RoyaltyAgreementIdentifierField.Equals(value) != true)) {
                    this.RoyaltyAgreementIdentifierField = value;
                    this.RaisePropertyChanged("RoyaltyAgreementIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScannerDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class ScannerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPausedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.Periodicities PeriodicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScannerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertScript {
            get {
                return this.AlertScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertScriptField, value) != true)) {
                    this.AlertScriptField = value;
                    this.RaisePropertyChanged("AlertScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarHistory {
            get {
                return this.BarHistoryField;
            }
            set {
                if ((this.BarHistoryField.Equals(value) != true)) {
                    this.BarHistoryField = value;
                    this.RaisePropertyChanged("BarHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarInterval {
            get {
                return this.BarIntervalField;
            }
            set {
                if ((this.BarIntervalField.Equals(value) != true)) {
                    this.BarIntervalField = value;
                    this.RaisePropertyChanged("BarInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exchange {
            get {
                return this.ExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeField, value) != true)) {
                    this.ExchangeField = value;
                    this.RaisePropertyChanged("Exchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPaused {
            get {
                return this.IsPausedField;
            }
            set {
                if ((this.IsPausedField.Equals(value) != true)) {
                    this.IsPausedField = value;
                    this.RaisePropertyChanged("IsPaused");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.Periodicities Periodicity {
            get {
                return this.PeriodicityField;
            }
            set {
                if ((this.PeriodicityField.Equals(value) != true)) {
                    this.PeriodicityField = value;
                    this.RaisePropertyChanged("Periodicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScannerName {
            get {
                return this.ScannerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ScannerNameField, value) != true)) {
                    this.ScannerNameField = value;
                    this.RaisePropertyChanged("ScannerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCodeDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class ServiceCodeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionalServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionalServiceCode {
            get {
                return this.FunctionalServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionalServiceCodeField, value) != true)) {
                    this.FunctionalServiceCodeField = value;
                    this.RaisePropertyChanged("FunctionalServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketCode {
            get {
                return this.MarketCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketCodeField, value) != true)) {
                    this.MarketCodeField = value;
                    this.RaisePropertyChanged("MarketCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSCode {
            get {
                return this.SMSCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSCodeField, value) != true)) {
                    this.SMSCodeField = value;
                    this.RaisePropertyChanged("SMSCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionStatuses", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.Enumerations")]
    public enum SubscriptionStatuses : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentModelTypes", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.Enumerations")]
    public enum PaymentModelTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trial = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.Enumerations")]
    public enum Product : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoProduct = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuoteBoardLite = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuoteBoardPro = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TraderLite = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TraderPro = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebTrader = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terminal = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.Enumerations")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrator = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertType", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.Enumerations")]
    public enum AlertType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        News = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Script = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Order = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerageTypes", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.Enumerations")]
    public enum BrokerageTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sanlam_iTrade = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FundXchange = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstrumentDTO", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.DTOs")]
    [System.SerializableAttribute()]
    public partial class InstrumentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternateSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketSegmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternateSymbol {
            get {
                return this.AlternateSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternateSymbolField, value) != true)) {
                    this.AlternateSymbolField = value;
                    this.RaisePropertyChanged("AlternateSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exchange {
            get {
                return this.ExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeField, value) != true)) {
                    this.ExchangeField = value;
                    this.RaisePropertyChanged("Exchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISIN {
            get {
                return this.ISINField;
            }
            set {
                if ((object.ReferenceEquals(this.ISINField, value) != true)) {
                    this.ISINField = value;
                    this.RaisePropertyChanged("ISIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketSegment {
            get {
                return this.MarketSegmentField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketSegmentField, value) != true)) {
                    this.MarketSegmentField = value;
                    this.RaisePropertyChanged("MarketSegment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Security {
            get {
                return this.SecurityField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityField, value) != true)) {
                    this.SecurityField = value;
                    this.RaisePropertyChanged("Security");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salutations", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State.Enumerations")]
    public enum Salutations : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mr = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mrs = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Miss = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ms = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dr = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Periodicities", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.State")]
    public enum Periodicities : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Secondly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Minutely = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hourly = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.ActionResults")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FundXchange.Model.AuthenticationService.RecoverPasswordResult))]
    public partial class ActionResultOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FundXchange.Model.AuthenticationService.ResultTypes ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((this.ObjectField.Equals(value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FundXchange.Model.AuthenticationService.ResultTypes Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecoverPasswordResult", Namespace="http://schemas.datacontract.org/2004/07/FundXchange.Services.ActionResults")]
    [System.SerializableAttribute()]
    public partial class RecoverPasswordResult : FundXchange.Model.AuthenticationService.ActionResultOfboolean {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.IAuthenticationService")]
    public interface IAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/GetUser", ReplyAction="http://tempuri.org/IAuthenticationService/GetUserResponse")]
        FundXchange.Model.AuthenticationService.UserResult GetUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/RecoverPassword", ReplyAction="http://tempuri.org/IAuthenticationService/RecoverPasswordResponse")]
        FundXchange.Model.AuthenticationService.RecoverPasswordResult RecoverPassword(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationServiceChannel : FundXchange.Model.AuthenticationService.IAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<FundXchange.Model.AuthenticationService.IAuthenticationService>, FundXchange.Model.AuthenticationService.IAuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FundXchange.Model.AuthenticationService.UserResult GetUser(string username, string password) {
            return base.Channel.GetUser(username, password);
        }
        
        public FundXchange.Model.AuthenticationService.RecoverPasswordResult RecoverPassword(string email) {
            return base.Channel.RecoverPassword(email);
        }
    }
}
