//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MarketModel11.proto
namespace Fin24.LiveData.Common.Protocol.DataFeed
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JSERawMessage")]
  public partial class JSERawMessage : global::ProtoBuf.IExtensible
  {
    public JSERawMessage() {}
    

    private long _TimeReceivedAsTicks = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"TimeReceivedAsTicks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long TimeReceivedAsTicks
    {
      get { return _TimeReceivedAsTicks; }
      set { _TimeReceivedAsTicks = value; }
    }

    private string _RawMessage = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RawMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RawMessage
    {
      get { return _RawMessage; }
      set { _RawMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
