//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MarketModel1.proto
namespace Fin24.LiveData.Common.Protocol.DataFeed
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckMessage")]
  public partial class AckMessage : global::ProtoBuf.IExtensible
  {
    public AckMessage() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
