//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MarketModel4.proto
namespace Fin24.LiveData.Common.Protocol.DataFeed
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SocketHandshakeRequest")]
  public partial class SocketHandshakeRequest : global::ProtoBuf.IExtensible
  {
    public SocketHandshakeRequest() {}
    

    private string _Username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Username
    {
      get { return _Username; }
      set { _Username = value; }
    }

    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }

    private string _CustomCredentials = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CustomCredentials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CustomCredentials
    {
      get { return _CustomCredentials; }
      set { _CustomCredentials = value; }
    }

    private string _Context = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Context
    {
      get { return _Context; }
      set { _Context = value; }
    }

    private string _VendorId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"VendorId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string VendorId
    {
      get { return _VendorId; }
      set { _VendorId = value; }
    }

    private string _ProductId = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ProductId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ProductId
    {
      get { return _ProductId; }
      set { _ProductId = value; }
    }

    private bool _ForceSessionOverride = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ForceSessionOverride", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ForceSessionOverride
    {
      get { return _ForceSessionOverride; }
      set { _ForceSessionOverride = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
