//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MarketModel8.proto
namespace Fin24.LiveData.Common.Protocol.DataFeed
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddSubscriptionCommand")]
  public partial class AddSubscriptionCommand : global::ProtoBuf.IExtensible
  {
    public AddSubscriptionCommand() {}
    

    private string _ExchangeName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ExchangeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ExchangeName
    {
      get { return _ExchangeName; }
      set { _ExchangeName = value; }
    }

    private string _ItemCode = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ItemCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ItemCode
    {
      get { return _ItemCode; }
      set { _ItemCode = value; }
    }

    private Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel _SubscriptionLevel = Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel.None;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SubscriptionLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel.None)]
    public Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel SubscriptionLevel
    {
      get { return _SubscriptionLevel; }
      set { _SubscriptionLevel = value; }
    }

    private string _SessionId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SessionId
    {
      get { return _SessionId; }
      set { _SessionId = value; }
    }

    private string _ProductId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ProductId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ProductId
    {
      get { return _ProductId; }
      set { _ProductId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveSubscriptionCommand")]
  public partial class RemoveSubscriptionCommand : global::ProtoBuf.IExtensible
  {
    public RemoveSubscriptionCommand() {}
    

    private string _ExchangeName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ExchangeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ExchangeName
    {
      get { return _ExchangeName; }
      set { _ExchangeName = value; }
    }

    private string _ItemCode = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ItemCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ItemCode
    {
      get { return _ItemCode; }
      set { _ItemCode = value; }
    }

    private Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel _SubscriptionLevel = Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel.None;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SubscriptionLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel.None)]
    public Fin24.LiveData.Common.Protocol.DataFeed.SubscriptionLevel SubscriptionLevel
    {
      get { return _SubscriptionLevel; }
      set { _SubscriptionLevel = value; }
    }

    private string _SessionId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SessionId
    {
      get { return _SessionId; }
      set { _SessionId = value; }
    }

    private string _ProductId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ProductId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ProductId
    {
      get { return _ProductId; }
      set { _ProductId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SubscriptionLevel")]
    public enum SubscriptionLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Level1", Value=1)]
      Level1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Level2", Value=2)]
      Level2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Level2Restricted", Value=4)]
      Level2Restricted = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Index", Value=8)]
      Index = 8
    }
  
}
