//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MarketModel6.proto
namespace Fin24.LiveData.Common.Protocol.DataFeed
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StringMessage")]
  public partial class StringMessage : global::ProtoBuf.IExtensible
  {
    public StringMessage() {}
    

    private string _Text = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
