//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MarketModel7.proto
namespace Fin24.LiveData.Common.DTOs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderbookDto")]
  public partial class OrderbookDto : global::ProtoBuf.IExtensible
  {
    public OrderbookDto() {}
    
    private readonly global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.DepthItemDto> _Bids = new global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.DepthItemDto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Bids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.DepthItemDto> Bids
    {
      get { return _Bids; }
    }
  
    private readonly global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.DepthItemDto> _Offers = new global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.DepthItemDto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Offers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.DepthItemDto> Offers
    {
      get { return _Offers; }
    }
  

    private long _LastMessageNumberProcessed = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LastMessageNumberProcessed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long LastMessageNumberProcessed
    {
      get { return _LastMessageNumberProcessed; }
      set { _LastMessageNumberProcessed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DepthItemDto")]
  public partial class DepthItemDto : global::ProtoBuf.IExtensible
  {
    public DepthItemDto() {}
    

    private long _Price = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Price
    {
      get { return _Price; }
      set { _Price = value; }
    }

    private long _Volume = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private readonly global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.OrderDto> _Orders = new global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.OrderDto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Orders", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Fin24.LiveData.Common.DTOs.OrderDto> Orders
    {
      get { return _Orders; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderDto")]
  public partial class OrderDto : global::ProtoBuf.IExtensible
  {
    public OrderDto() {}
    

    private string _BDG = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"BDG", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BDG
    {
      get { return _BDG; }
      set { _BDG = value; }
    }

    private string _MessageType = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MessageType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MessageType
    {
      get { return _MessageType; }
      set { _MessageType = value; }
    }

    private bool _IsResendIndicator = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"IsResendIndicator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsResendIndicator
    {
      get { return _IsResendIndicator; }
      set { _IsResendIndicator = value; }
    }

    private long _SequenceNumber = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SequenceNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long SequenceNumber
    {
      get { return _SequenceNumber; }
      set { _SequenceNumber = value; }
    }

    private int _GlobalMessageNumber = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"GlobalMessageNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GlobalMessageNumber
    {
      get { return _GlobalMessageNumber; }
      set { _GlobalMessageNumber = value; }
    }

    private int _AgentMessageNumber = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"AgentMessageNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AgentMessageNumber
    {
      get { return _AgentMessageNumber; }
      set { _AgentMessageNumber = value; }
    }

    private string _TradableInstrumentCode = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"TradableInstrumentCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TradableInstrumentCode
    {
      get { return _TradableInstrumentCode; }
      set { _TradableInstrumentCode = value; }
    }

    private string _Symbol = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Symbol
    {
      get { return _Symbol; }
      set { _Symbol = value; }
    }

    private string _ExchangeCode = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ExchangeCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ExchangeCode
    {
      get { return _ExchangeCode; }
      set { _ExchangeCode = value; }
    }

    private string _SegmentCode = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"SegmentCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SegmentCode
    {
      get { return _SegmentCode; }
      set { _SegmentCode = value; }
    }

    private string _SectorCode = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"SectorCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SectorCode
    {
      get { return _SectorCode; }
      set { _SectorCode = value; }
    }

    private string _CountryOfRegister = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"CountryOfRegister", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CountryOfRegister
    {
      get { return _CountryOfRegister; }
      set { _CountryOfRegister = value; }
    }

    private string _CurrencyCode = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"CurrencyCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CurrencyCode
    {
      get { return _CurrencyCode; }
      set { _CurrencyCode = value; }
    }

    private string _ParticipantCode = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ParticipantCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ParticipantCode
    {
      get { return _ParticipantCode; }
      set { _ParticipantCode = value; }
    }

    private string _BuySellIndicator = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"BuySellIndicator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BuySellIndicator
    {
      get { return _BuySellIndicator; }
      set { _BuySellIndicator = value; }
    }

    private string _MarketMechanismGroup = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"MarketMechanismGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MarketMechanismGroup
    {
      get { return _MarketMechanismGroup; }
      set { _MarketMechanismGroup = value; }
    }

    private string _PrivateOrderCode = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"PrivateOrderCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PrivateOrderCode
    {
      get { return _PrivateOrderCode; }
      set { _PrivateOrderCode = value; }
    }

    private string _MarketMechanismType = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"MarketMechanismType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MarketMechanismType
    {
      get { return _MarketMechanismType; }
      set { _MarketMechanismType = value; }
    }

    private long _OrderPrice = default(long);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"OrderPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long OrderPrice
    {
      get { return _OrderPrice; }
      set { _OrderPrice = value; }
    }

    private long _AggregateSize = default(long);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"AggregateSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AggregateSize
    {
      get { return _AggregateSize; }
      set { _AggregateSize = value; }
    }

    private string _Capacity = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"Capacity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Capacity
    {
      get { return _Capacity; }
      set { _Capacity = value; }
    }

    private string _TimeValidity = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"TimeValidity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TimeValidity
    {
      get { return _TimeValidity; }
      set { _TimeValidity = value; }
    }

    private string _DateValidity = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"DateValidity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DateValidity
    {
      get { return _DateValidity; }
      set { _DateValidity = value; }
    }

    private string _PersonalExposure = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"PersonalExposure", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PersonalExposure
    {
      get { return _PersonalExposure; }
      set { _PersonalExposure = value; }
    }

    private string _OrderReference = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"OrderReference", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OrderReference
    {
      get { return _OrderReference; }
      set { _OrderReference = value; }
    }

    private string _ClientReference = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"ClientReference", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ClientReference
    {
      get { return _ClientReference; }
      set { _ClientReference = value; }
    }

    private string _SingleFillIndicator = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"SingleFillIndicator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SingleFillIndicator
    {
      get { return _SingleFillIndicator; }
      set { _SingleFillIndicator = value; }
    }

    private string _BroadcastUpdateAction = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"BroadcastUpdateAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BroadcastUpdateAction
    {
      get { return _BroadcastUpdateAction; }
      set { _BroadcastUpdateAction = value; }
    }

    private long _TimeMessageReceivedAsTicks = default(long);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"TimeMessageReceivedAsTicks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long TimeMessageReceivedAsTicks
    {
      get { return _TimeMessageReceivedAsTicks; }
      set { _TimeMessageReceivedAsTicks = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
